### ISSUE TITLE
ParserTest fails with "ERROR: can not mix dimensionality in a geometry"

### ISSUE THREAD

**Issue by phillipross** [postgis/postgis-java#17]
When run against the database, the ParserTest test class fails.

When the class fails, it's sending this data in the test dataset:
`GEOMETRYCOLLECTIONM(POINT(10 10 20),POINT(20 20 20))`

https://github.com/postgis/postgis-java/blob/master/jdbc/src/test/java/org/postgis/ParserTest.java#L165

stacktrace:
<pre>org.postgresql.util.PSQLException: ERROR: can not mix dimensionality in a geometry
  Hint: "...ONM(POINT(10 10 20),POINT(20 20 20))" <-- parse error at position 53 within geometry
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2103)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1836)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:512)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:254)
	at org.postgis.ParserTest.viaSQL(ParserTest.java:373)
	at org.postgis.ParserTest.test(ParserTest.java:290)
	at org.postgis.ParserTest.testParser(ParserTest.java:242)</pre>

The equivalent function fails when run from psql:
<pre>
postgis1=> select geometry_in('GEOMETRYCOLLECTIONM(POINT(10 10 20),POINT(20 20 20))');
ERROR:  can not mix dimensionality in a geometry
HINT:  "...ONM(POINT(10 10 20),POINT(20 20 20))" <-- parse error at position 53 within geometry
</pre>

**Comment by phillipross** [comment]
This is correct behavior exhibited by PostGIS (per @strk ) so the [ParserTest](https://github.com/phillipross/postgis-java/blob/0495cb304f705ae7b1281c4307ae54d1213b2fac/jdbc/src/test/java/org/postgis/ParserTest.java)  class was updated on change 0495cb304f705ae7b1281c4307ae54d1213b2fac and integrated with pull request #22 to rework test dataset to **no*t* use this faulty geometry, but rather a dimensionally consistent version.
